import termcolor
import time
answer = input('would you like to delete the file "root/c/python/script/firewall/proxy"? [y/n] ')
if answer == "y":
    termcolor.cprint('deleting file...','blue')
    time.sleep(2)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    print('deleting file: root/c/python/script/firewall/proxy')
    time.sleep(0.005)
    termcolor.cprint('cannot delete files. instalation needed.','red')
    time.sleep(2)
    anser = input('would you like to install the required file? [yes/no] ')
    if anser == "yes":
        print('#------')
        time.sleep(0.5)
        print('##-----')
        time.sleep(0.5)
        print('###----')
        time.sleep(0.5)
        print('####---')
        time.sleep(0.5)
        print('#####--')
        time.sleep(0.5)
        print('######-')
        time.sleep(0.5)
        print('#######')
        time.sleep(3)
        print('instalation completed and files deleted. task executed sucsessfully')
    if anser == "no":
        print('task failed. required file not found.')
if answer == "n":
    print('will not delete file.')
